# Site settings
title: "Miguel Cruz's Blog"
header-img: img/home-bg.jpg
email: miguel_at_miguelcruz_dot_net
description: "Write your site description here. It will be used as your sites meta description as well!"
homeurl: "http://www.miguelcruz.net"
baseurl: ""
url: "http://blog.miguelcruz.net"
twitter_username: miguelcruznet
github_username:  duber

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: "UA-70145134-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
